//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class myTable
    {
        public double ID { get; set; }
        public string Наименование_услуги { get; set; }
        public Nullable<double> Стоимость { get; set; }

        public myTable()
        {

        }

        public myTable(double iD, string наименование_услуги, double? sтоимость)
        {
            ID = iD;
            Наименование_услуги = наименование_услуги;
            Стоимость = sтоимость;
        }
    }


}
